CERTAPPIDENTITY=3rd Party Mac Developer Application: Planamesa Inc (8V953UDD5Q)
CERTPKGIDENTITY=3rd Party Mac Developer Installer: Planamesa Inc (8V953UDD5Q)
CERTAPPIDENTITY2=Developer ID Application: Planamesa Inc
CERTPKGIDENTITY2=Developer ID Installer: Planamesa Inc
CERTAPPIDENTITY3=Developer ID Application: Planamesa Inc
CERTPKGIDENTITY3=Developer ID Installer: Planamesa Inc
CERTSANDBOXTEAMIDENTIFIER=8V953UDD5Q
PATCHCERTAPPIDENTITY=Developer ID Application: Planamesa Inc
PATCHCERTPKGIDENTITY=Developer ID Installer: Planamesa Inc
PATCHCERTAPPIDENTITY2=Developer ID Application: Planamesa Inc
PATCHCERTPKGIDENTITY2=Developer ID Installer: Planamesa Inc
PATCHCERTAPPIDENTITY3=Developer ID Application: Planamesa Inc
PATCHCERTPKGIDENTITY3=Developer ID Installer: Planamesa Inc
APPLEDEVELOPERID=
