.PHONY: build.neo_configure_phony

build.neo_configure_phony:
	rm -f "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export GUIBASE=java" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_BUILD_TYPE=java" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_NAME='$(PRODUCT_NAME)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_DIR_NAME='$(PRODUCT_DIR_NAME)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_DIR_NAME2='$(PRODUCT_DIR_NAME2)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_DIR_NAME3='$(PRODUCT_DIR_NAME3)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_DOMAIN='$(PRODUCT_DOMAIN)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_FILETYPE='$(PRODUCT_FILETYPE)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_MAC_APP_STORE_URL='$(PRODUCT_MAC_APP_STORE_URL)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_JAVA_DOWNLOAD_URL='$(PRODUCT_JAVA_DOWNLOAD_URL)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_MIN_OSVERSION='$(PRODUCT_MIN_OSVERSION)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
	echo "export PRODUCT_MAX_OSVERSION='$(PRODUCT_MAX_OSVERSION)'" >> "$(LIBO_OVERRIDDEN_ENVVARS)"
